config/routes.rb
RsvpOnline::Application.routes.draw do
  root 'weddings#home'

  match '/',        to: 'weddings#home',    via: 'get'
  match '/venue',   to: 'weddings#venue',   via: 'get'
  match '/events',  to: 'weddings#events',  via: 'get'
  match '/rsvp',    to: 'weddings#rsvp',    via: 'get'
  match '/photos',  to: 'weddings#photos',  via: 'get'

  match '/admin',        to: 'admin#settings',     via: 'get'
  match '/verify_admin', to: 'admin#verify_admin', via: 'post'
  match '/sign_in',      to: 'session#sign_in',    via: 'get'
  match '/sign_out',     to: 'session#sign_out',   via: 'get'

  match '/gift/send',                to: 'campaigns#show',                                        via: 'get'
  match '/gift/payment/:id',         to: 'campaigns#process_payment',   as: '/gift/payment',      via: 'get'
  match '/gift/confirmation/:id',    to: 'campaigns#gift_confirmation', as: '/gift/confirmation', via: 'get'
  match '/campaign/find_user',       to: 'campaigns#user',                                        via: 'get'

  resources :users
  resources :weddings
  resources :campaigns
  resources :payments
  resources :session, :only => [:create, :destroy]

 

  

end

app/models/Item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :name 
  validates_presence_of :description  
	validates_presence_of :quantity 
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	has_many :payments
	accepts_nested_attributes_for :payments
end

app/models/campaigns.rb
class Campaigns < ActiveRecord::Base
end

app/models/guest.rb
class Guest < ActiveRecord::Base
end

app/models/items.rb
class Items < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	validates :fullname, presence: true
	validates :email, presence: true
	belongs_to :campaign
end

app/models/user.rb
class User < ActiveRecord::Base
	#should have used a different name
	has_many :guests, :class_name => 'User', :foreign_key => :host_id
	validates_presence_of :name
	validates_presence_of :email
	has_secure_password
end

app/models/users.rb
class Users < ActiveRecord::Base
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :check_privledges
	
	def settings
		if Wedding.first.nil?
			@wedding = Wedding.new
		else 
			@wedding = Wedding.first
		end
		if Campaign.first.nil?
			@campaign = Campaign.new
		else
			@campaign = Campaign.first
		end
	end

	def verify_admin #turn into get user
		check_user(current_user)
		verification = {
			name: params[:name],
			dob:  params[:dob],
			phone_number: params[:number],
			street_address: params[:street_address],
			postal_code: params[:postal_code]}
			#Crowdtilt.production  
			response = Crowdtilt.post("/users/#{current_user.ct_id}/verification", {verification: verification})  
		end


		private 

		def check_privledges
			unless current_user && current_user.is_admin
				redirect_to root_path
			end
		end

	end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
	def index
    @gifts = Guest.all
  end

  def show
    @gift = Guest.find(params[:id])
  end

  def new
    @gift = Guest.new
  end

  def edit
    @gift = Guest.find(params[:id])
  end

  def create
    @gift = Guest.new(params[:Guest])
    
  end

  def update
    @gift = Guest.find(params[:id])
  end

  def destroy
    @gift = Guest.find(params[:id])
    @gift.destroy
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
	def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def create
    @guest = Guest.new(params[:Guest])
    
  end

  def update
    @guest = Guest.find(params[:id])
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	def sign_in

	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:id] = user.id
			redirect_to your_profile_path, notice: "Signed in!"
		else
			flash[:errors] = {"Login" => ["Email and Password combination not found"]}
			redirect_to root_path
		end
	end

	def sign_out
		session.clear
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      # UserMailer.signup_confirmation(@user.id).deliver
      redirect_to admin_path, notice: "You've successfully signed up!"
    else
      flash[:errors] = @user.errors.messages
      render 'session/sign_in'
    end
  end

  def destroy
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/gift_helper.rb
module GiftHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wedding_helper.rb
module WeddingHelper
end

app/views/gift/index.html.erb
<form action="#" method="POST" id="cardForm">
    <input type="hidden" name="user_id">           
    <fieldset>
        <label>Card Number</label>
        <input type="text" name="card_number" autocomplete="off">
    </fieldset>
    <fieldset>
        <label>Expiration</label>             
        <select name="expiration_month" style="width:50px">
            <option value="01" selected>01</option>
            <option value="02">02</option>
            <option value="03">03</option>
            <option value="04">04</option>
            <option value="05">05</option>
            <option value="06">06</option>
            <option value="07">07</option>
            <option value="08">08</option>
            <option value="09">09</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
        </select>

        <select name="expiration_year" style="width:75px">
            <option value="2013" selected>2013</option>
            <option value="2014">2014</option>
            <option value="2015">2015</option>
            <option value="2016">2016</option>
            <option value="2017">2017</option>
            <option value="2018">2018</option>
            <option value="2019">2019</option>
            <option value="2020">2020</option>
        </select>
    </fieldset>
    <fieldset>
        <label>Security Code</label>
        <input type="text" name="security_code" autocomplete="off">
    </fieldset>
    <button type="submit">submit</button>
</form>

<form action="#" method="POST" id="bankForm">
    <input type="hidden" name="user_id">      
    <fieldset>
        <label>Bank Name</label>
        <input type="text" name="name">
    </fieldset>
    <fieldset>
        <label>Account Number</label>
        <input type="text" name="account_number" autocomplete="off">
    </fieldset>
    <fieldset>
        <label>Bank Code (Routing Number in USA)</label>
        <input type="text" name="bank_code">
    </fieldset>

    <button type="submit">submit</button>
</form>
<script type="text/javascript" src="https://api.crowdtilt.com/v1/js/crowdtilt.js"></script>

app/views/gifts/index.html.erb
<form action="#" method="POST" id="cardForm">
    <input type="hidden" name="user_id" value='USR51155A6EF2B311E28635B37C6E84F691'>           
    <fieldset>
        <label>Card Number</label>
        <input type="text" name="card_number" autocomplete="off">
    </fieldset>
    <fieldset>
        <label>Expiration</label>             
        <select name="expiration_month" style="width:50px">
            <option value="01" selected>01</option>
            <option value="02">02</option>
            <option value="03">03</option>
            <option value="04">04</option>
            <option value="05">05</option>
            <option value="06">06</option>
            <option value="07">07</option>
            <option value="08">08</option>
            <option value="09">09</option>
            <option value="10">10</option>
            <option value="11">11</option>
            <option value="12">12</option>
        </select>

        <select name="expiration_year" style="width:75px">
            <option value="2013" selected>2013</option>
            <option value="2014">2014</option>
            <option value="2015">2015</option>
            <option value="2016">2016</option>
            <option value="2017">2017</option>
            <option value="2018">2018</option>
            <option value="2019">2019</option>
            <option value="2020">2020</option>
        </select>
    </fieldset>
    <fieldset>
        <label>Security Code</label>
        <input type="text" name="security_code" autocomplete="off">
    </fieldset>
    <button type="submit">submit</button>
</form>

</form>
<script type="text/javascript" src="https://api.crowdtilt.com/v1/js/crowdtilt.js"></script>

app/views/session/sign_in.html.erb
<div>
  <fieldset>
    <%= form_tag session_index_path, :class => "login"  do %>
    <%= email_field_tag :email, nil, placeholder: "Email" %><br>
    <%= password_field_tag :password, nil, placeholder: "Password" %><br><br>
    <%= submit_tag "Log In", class: "btn btn-success" %>
    <% end %>
  </fieldset>
</div>

<div>
  <fieldset>
    <% @user = User.new %>
    <%= form_for @user do |f| %>

    <%= f.text_field :name, :id => "inputName", :required => true, placeholder: "Name" %><br>

    <%= f.email_field :email, :id => "inputEmail", :required => true, placeholder: "Email" %><br>

    <%= f.password_field :password, :id => "inputPassword", :required => true, placeholder: "Password" %><br>
    <%= f.password_field :password_confirmation , :id => "inputPassword", :required => true, placeholder: "Password" %><br>

    <div>
      <span class='left'>stuff</span>    <span><%= f.submit "Sign up", :class => 'button right' %></span>
    </div>
    <% end %>
  </fieldset>
</div>