config/routes.rb
RsvpOnline::Application.routes.draw do
  root 'weddings#home'

  match '/',        to: 'weddings#home',    via: 'get'
  match '/venue',   to: 'weddings#venue',   via: 'get'
  match '/events',  to: 'weddings#events',  via: 'get'
  match '/rsvp',    to: 'weddings#rsvp',    via: 'get'
  match '/photos',  to: 'weddings#photos',  via: 'get'

  match '/admin',        to: 'admin#settings',     via: 'get'
  match '/verify_admin', to: 'admin#verify_admin', via: 'post'
  match '/sign_in',      to: 'session#sign_in',    via: 'get'
  match '/sign_out',     to: 'session#sign_out',   via: 'get'

  match '/gift/send',                to: 'campaigns#show',                                        via: 'get'
  match '/gift/payment/:id',         to: 'campaigns#process_payment',   as: '/gift/payment',      via: 'get'
  match '/gift/confirmation/:id',    to: 'campaigns#gift_confirmation', as: '/gift/confirmation', via: 'get'
  match '/campaign/find_user',       to: 'campaigns#user',                                        via: 'get'

  resources :users
  resources :weddings
  resources :campaigns
  resources :payments
  resources :session, :only => [:create, :destroy]

 

  

end

app/models/Item.rb
class Item < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :name 
  validates_presence_of :description  
	validates_presence_of :quantity 
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
	has_many :payments
	accepts_nested_attributes_for :payments
end

app/models/campaigns.rb
class Campaigns < ActiveRecord::Base
end

app/models/guest.rb
class Guest < ActiveRecord::Base
end

app/models/items.rb
class Items < ActiveRecord::Base
end

app/models/payment.rb
class Payment < ActiveRecord::Base
	validates :fullname, presence: true
	validates :email, presence: true
	belongs_to :campaign
end

app/models/user.rb
class User < ActiveRecord::Base
	#should have used a different name
	has_many :guests, :class_name => 'User', :foreign_key => :host_id
	validates_presence_of :name
	validates_presence_of :email
	has_secure_password
end

app/models/users.rb
class Users < ActiveRecord::Base
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_filter :check_privledges
	
	def settings
		if Wedding.first.nil?
			@wedding = Wedding.new
		else 
			@wedding = Wedding.first
		end
		if Campaign.first.nil?
			@campaign = Campaign.new
		else
			@campaign = Campaign.first
		end
	end

	def verify_admin #turn into get user
		check_user(current_user)
		verification = {
			name: params[:name],
			dob:  params[:dob],
			phone_number: params[:number],
			street_address: params[:street_address],
			postal_code: params[:postal_code]}
			#Crowdtilt.production  
			response = Crowdtilt.post("/users/#{current_user.ct_id}/verification", {verification: verification})  
		end


		private 

		def check_privledges
			unless current_user && current_user.is_admin
				redirect_to root_path
			end
		end

	end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

	def new
		@campaign = Campaign.new
	end

	def show
		@wedding = Wedding.first
		@campaign = Campaign.first
		@payment = Payment.new
	end

	def create
		@campaign = Campaign.new(campaign_params)
		if current_user.ct_id.nil?
			user = Crowdtilt.create_user(email: current_user.email)
		end
		if @campaign.save
			campaign ={
				title: @campaign.title,
				expiration_date: @campaign.expiration_date,
				tilt_amount: 100,
        user_id: current_user.ct_id
			}
			begin
				#Crowdtilt.production
				response = Crowdtilt.post('/campaigns', {campaign: campaign})
				@campaign.update_attributes!(ct_campaign_id: user["campaign"]["id"])
				redirect_to admin_path
			rescue => exception
				flash.now[:error] = exception.to_s
				render 'admin/settings'
			end
		else
			render 'admin/settings', @errors = @campaign.errors.full_messages
		end
	end

	def process_payment
	
	end

	def gift_confirmation

	end

	private

	def campaign_params
		params.require(:campaign).permit(:title,:expiration_date, :note, :image_file_name)
	end
end

 # t.string   "ct_payment_id"
 #    t.string   "status"
 #    t.integer  "amount"
 #    t.string   "fullname"
 #    t.string   "email"
 #    t.string   "card_type"
 #    t.string   "card_last_four"
 #    t.string   "card_expiration_month"
 #    t.string   "card_expiration_year"
 #    t.integer  "campaign_id"
 #    t.string   "address_one"
 #    t.string   "address_two"
 #    t.string   "city"
 #    t.string   "state"
 #    t.string   "postal_code"
 #    t.string   "country"
 #    t.integer  "quantity"
 #    t.text     "additional_info"
 #    t.datetime "created_at"
 #    t.datetime "updated_at"

#schema
    # t.string   "title"
    # t.datetime "expiration_date"
    # t.string   "ct_campaign_id"
    # t.string   "image_file_name"
    # t.text     "note"
    # t.integer  "tilt_amount",     default: 1, null: false
    # t.datetime "created_at"
    # t.datetime "updated_at"

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
	def index
    @gifts = Guest.all
  end

  def show
    @gift = Guest.find(params[:id])
  end

  def new
    @gift = Guest.new
  end

  def edit
    @gift = Guest.find(params[:id])
  end

  def create
    @gift = Guest.new(params[:Guest])
    
  end

  def update
    @gift = Guest.find(params[:id])
  end

  def destroy
    @gift = Guest.find(params[:id])
    @gift.destroy
  end

end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
	def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def create
    @guest = Guest.new(params[:Guest])
    
  end

  def update
    @guest = Guest.find(params[:id])
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

	def sign_in

	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:id] = user.id
			redirect_to your_profile_path, notice: "Signed in!"
		else
			flash[:errors] = {"Login" => ["Email and Password combination not found"]}
			redirect_to root_path
		end
	end

	def sign_out
		session.clear
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      # UserMailer.signup_confirmation(@user.id).deliver
      redirect_to admin_path, notice: "You've successfully signed up!"
    else
      flash[:errors] = @user.errors.messages
      render 'session/sign_in'
    end
  end

  def destroy
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/wedding_controller.rb
class WeddingController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/gift_helper.rb
module GiftHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wedding_helper.rb
module WeddingHelper
end

app/views/campaigns/new.html.haml
%h1 Create a new Campaign 
%p Set up a Crowdtilt Account
.ct-admin-verify
	=form_tag verify_admin_path, :method => :post do
		=text_field_tag(:name, nil, placeholder:'Full legal name')
		=text_field_tag(:DOB,nil, placeholder:'Date of birth')
		=text_field_tag(:phone_number,nil, placeholder:'Telephone number')
		=text_field_tag(:street_address,nil, placeholder:'Your street address')
		=text_field_tag(:postal_code,nil, placeholder:'Your postal code')
		=submit_tag 

app/views/campaigns/show.html.haml
.large-10.columns.large-centered
	%h1.fancy Send a gift to #{@wedding.couple_name}
	=	form_for @payment do |f|
		.row
			.large-6.columns
				%label Full Name
				= f.text_field(:fullname, placeholder: 'John Smith', :required => 'true' )
			.large-6.columns
				%label Email
				= f.email_field(:email, placeholder: 'john@example.com', :required => 'true')
		.row	
			.large-5.columns
				%label Address
				=f.text_field(:address_one)	
			.large-3.columns
				%label City
				=f.text_field(:city)	
			.large-1.columns
				%label State
				=f.text_field(:state)	
			.large-3.columns
				%label Postal Code
				=f.text_field(:postal_code)	
		.row
			.large-3.columns
				%label Gift Amount
				.row.collapse
					.small-1.large-4.columns
						%span.prefix $
					.small-3.large-8.columns
						= f.text_field(:amount, placeholder: '20.00', :required => 'true')
			.large-4.small-3.columns
				%label Card Number
				%input{:type => "text", :name => "card_number", :required => 'true'}
			.large-2.small-3.columns
				%label CCV
				%input{:type => "text", :name => "security_code", :required => 'true'}
			.large-1.small-3.columns
				%label Month
				= f.select(:card_expiration_month, ["01", "02", "03", "04", "05", '06', '07','08','09', '10', '11', '12'], :required => 'true', )
			.large-2.small-3.columns
				%label Year
				= f.select(:card_expiration_year, (2013..2025).to_a, :required => 'true')	
		.row	
			.large-12.columns	
				= f.submit 'Continue', :class => 'button right'
			.large-12.columns	
				%h6.subheader Payment processing provided by Crowdtilt




/ PUT /users/:id/cards/:id



/schema
/ create_table :payments, :force => true  do |t|

/ 			t.string   "status"
/ 			t.integer  "amount"
/ 			t.string   "fullname"
/ 			t.string   "email"
/ 			t.timestamps


/ 			t.string   "card_type"
/ 			t.string   "card_last_four"
/ 			t.string   "card_expiration_month"
/ 			t.string   "card_expiration_year"
/ 			t.integer  "campaign_id"
/ 			t.string   "address_one"
/ 			t.string   "address_two"
/ 			t.string   "city"
/ 			t.string   "state"
/ 			t.string   "postal_code"
/ 			t.string   "country"
/ 			t.string   "ct_payment_id"
/ {